runtime: python

entrypoint: gunicorn -b :$PORT Breeze18.wsgi 
env: flex

env_variables:

  SECRET_KEY: '!lct&871ornh%2x-8s%5!3yi=2d54mo94d)d1quft@pr*nu8$l'
  DEBUG: 'False' 

  DB_HOST: '/cloudsql/breeze19:asia-southeast1:breeze19-db'
  DB_PORT: '5432' 
  DB_NAME: 'breeze19_data'
  DB_USER: 'admiin' 
  DB_PASSWORD: 'dontdie@Breeze19@Admin'
  
  STATIC_URL: 'https://storage.googleapis.com/breeze19-static/static/' 
  
handlers:
- url: /static
  static_dir: static

beta_settings:
  
  cloud_sql_instances: breeze19:asia-southeast1:breeze19-db 

runtime_config:
  python_version: 3