from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^19/$', views.nineteen, name='nineteen'),
    url(r'^events/$',views.get_events,name='register'),
    url(r'^events/sports/$',views.sports, name='sports'),
    url(r'^events/technical/$',views.technical, name='technical'),
    url(r'^events/cultural/$',views.cultural, name='cultural'),
    url(r'^events/(?P<category>\w+)/(?P<subcategory>\w+)$',views.specificEventView, name='events'),
    url(r'^signin/', views.signin, name='login'),
    url(r'^signup/', views.register, name='register'),
    url(r'^login/$',views.login1,name='login'),
    url(r'^createaccount/$',views.createaccount,name='createaccount'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}),
    url(r'^gallery/$', views.gallery,name='gallery'),
    url(r'^sponsors/$',views.sponsors,name='sponsors'),
    url(r'^team/$', views.team, name='team'),
    url(r'^events/register/$',views.event_register2, name='event_register2'),
    url(r'^19/accomodation/$', views.pdf_redirect, name='pdf_redirect'),
    url(r'^forgotpassmail',views.forgotpassmail,name='forgotpassmail'),
    url(r'^partners/$', views.partners, name='partners'),
    url(r'^transport/$', views.transport, name='transport'),
    url(r'^accommodation/$', views.accomodation, name='accomodation'),
    url(r'^events/register2/$',views.event_register, name='event_register'),
    url(r'^accommodation/register/$', views.accom_register, name='accom_register'),
    url(r'^accommodation/register2/$',views.accom_register2, name='accom_register2'),
    url(r'^pronights/', views.pronights, name='pronights'),
    url(r'^forgotpass/', views.forgotmail, name='forgotmail'),
    url(r'^forgotPassword/(?P<hashkey>\w+)', views.forgot, name='forgot'),
    url(r'^clubdashboard/', views.clubdashboard, name='clubdashboard'),
    url(r'^updateremarks/', views.updateremarks, name='updateremarks'),
    url(r'^me/', views.profile, name='profile'),
]
