# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('category', models.CharField(choices=[('c', 'Cultural'), ('s', 'Sports'), ('t', 'Technical')], default='c', help_text='category of event', max_length=1)),
                ('subCategory', models.CharField(help_text='eg Dance,Music,', max_length=50)),
                ('parentClub', models.CharField(help_text='eg Snuphoria,TEDx,', max_length=50)),
                ('contact', models.CharField(help_text='contact person(s) details', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Formdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=0, null=True)),
                ('gender', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=18)),
                ('college', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='Unpaid', max_length=200)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeze.Event')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeze.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='formdata',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeze.Registration'),
        ),
    ]
