# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0002_remove_profile_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='BreezeUser', max_length=18),
            preserve_default=False,
        ),
    ]
