# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 19:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0003_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_market',
            field=models.CharField(help_text='Marketing representative', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_pr',
            field=models.CharField(help_text='PR representative', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_spons',
            field=models.CharField(help_text='Sponsorship representative', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2018-02-09', help_text='Mention (start) date of the event'),
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(decimal_places=2, help_text='Registration fee for the event', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_market',
            field=models.CharField(blank=True, help_text='Marketing representative phone number', max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_pr',
            field=models.CharField(blank=True, help_text='PR Representative phone number', max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_spons',
            field=models.CharField(blank=True, help_text='Sponsorship representative phone number', max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.DecimalField(decimal_places=2, help_text='Prize Money for the event', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='B315', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('c', 'cultural'), ('s', 'sports'), ('t', 'technical')], default='c', help_text='category of event eg. Sports, Cultural, Technical', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='subCategory',
            field=models.CharField(help_text='eg Gaming,Dance,Music,Miscellaneous', max_length=50),
        ),
    ]
