# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0006_auto_20180110_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transaction_status',
            field=models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid')], default='u', max_length=1),
        ),
    ]
