# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Breeze', '0007_auto_20180111_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('college', models.CharField(default='', max_length=200)),
                ('registration_id', models.CharField(default='', max_length=200, unique=True)),
                ('transaction_status', models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid')], default='u', max_length=1)),
                ('packageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeze.Event')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Fee of the package', max_digits=8, null=True)),
            ],
        ),
    ]
