# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0008_accomregistration_accpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomregistration',
            name='packageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Breeze.AccPackage'),
        ),
    ]
