# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0009_auto_20180112_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomregistration',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
