# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0010_accomregistration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomregistration',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
