# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0011_auto_20180112_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomregistration',
            name='days',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
