# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 16:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0013_auto_20180112_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact_pr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_spons',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone_pr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone_spons',
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_market',
            field=models.CharField(blank=True, help_text='Name of Contact representative', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone_market',
            field=models.CharField(blank=True, help_text='Contact representative phone number', max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{10}$')]),
        ),
    ]
