# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0014_auto_20180112_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee_type',
            field=models.CharField(choices=[('head', 'Per Head'), ('team', 'Per Team')], default='head', help_text='type of pricing. Per head or per team', max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
