# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0015_auto_20180113_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
