# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0016_auto_20180113_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='number_of_participants',
            field=models.DecimalField(decimal_places=0, default=0, help_text='0 if not applicable to a event.', max_digits=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_status',
            field=models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid'), ('d', 'Discrepancy')], default='u', max_length=1),
        ),
    ]
