# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0018_auto_20180116_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accomregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='form_text',
            field=models.CharField(blank=True, default='', help_text='Text to show with Google Form URL in registration successful mail. Leave blank if no url', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='form_url',
            field=models.CharField(default='null', help_text='Google form link. null if no url', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='min_number',
            field=models.DecimalField(decimal_places=0, default=1, help_text='Number of minimum participants', max_digits=2),
        ),
        migrations.AddField(
            model_name='event',
            name='poster_name',
            field=models.CharField(blank=True, default='', help_text='Name of poster image file', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accomregistration',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
