# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0019_auto_20180117_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_number',
            field=models.DecimalField(decimal_places=0, default=50, help_text='Number of maximum participants', max_digits=2),
        ),
    ]
