# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0020_event_max_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee_snu',
            field=models.DecimalField(decimal_places=2, help_text='Registration fee for the event(SNU Students)', max_digits=8, null=True),
        ),
    ]
