# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-04 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0023_remove_event_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomregistration',
            name='packageId',
        ),
        migrations.RemoveField(
            model_name='accomregistration',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='forgetpass',
            name='user',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='userId',
        ),
        migrations.DeleteModel(
            name='AccomRegistration',
        ),
        migrations.DeleteModel(
            name='AccPackage',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ForgetPass',
        ),
        migrations.DeleteModel(
            name='Formdata',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
