# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0027_remove_events_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
