# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-11 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0029_auto_20190106_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payable',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(default=b'2018-02-09', help_text=b'Mention (start) date of the event', max_length=50),
        ),
    ]
