# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0030_auto_20190111_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='nop',
            field=models.DecimalField(decimal_places=0, default=b'-1', max_digits=3),
        ),
    ]
