# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-22 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0032_auto_20190116_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.CharField(default='2018-02-09', help_text='Mention (start) date of the event', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='prizes',
            field=models.CharField(default='', help_text='prize text for sports', max_length=150),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nop',
            field=models.DecimalField(decimal_places=0, default='-1', max_digits=3),
        ),
    ]
