# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0033_auto_20190122_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('rollno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=50)),
                ('yearofstudy', models.CharField(max_length=10)),
                ('parti', models.CharField(max_length=20)),
                ('regid', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='include',
            field=models.IntegerField(default=0, help_text='Set 1 to open registration and 0 to close'),
        ),
    ]
